### ISSUE TITLE
rhubarbe-pdu off not working

### ISSUE THREAD

**Issue by parmentelat** [fit-r2lab/rhubarbe#17]
```
root@faraday ~ (master) # rhubarbe-pdu off n320
Doing a soft TURN OFF on device {self.name}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rhubarbe/__main__.py", line 56, in main
    exit(entry_point(*args))
         ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rhubarbe/main.py", line 944, in pdu
    retcod = asyncio.run(device.run_action(command))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rhubarbe/inventorypdus.py", line 274, in run_action
    return await self.off()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rhubarbe/inventorypdus.py", line 220, in off
    await self.attempt_soft_reset()
  File "/usr/local/lib/python3.11/site-packages/rhubarbe/inventorypdus.py", line 167, in attempt_soft_reset
    soft_turned_off = await self.turn_off_through_ssh_if_pingable()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rhubarbe/inventorypdus.py", line 163, in turn_off_through_ssh_if_pingable
    return completed.returncode == 0
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'returncode'
/usr/local/bin/rhubarbe-pdu pdu : Something went badly wrong : 'coroutine' object has no attribute 'returncode'
sys:1: RuntimeWarning: coroutine 'SSHClientConnection.run' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

```

**Comment by parmentelat** [comment]
fixed in release 5.2.1
